services:
  - type: web
    name: cruzados-server
    env: node
    rootDirectory: server
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
